### PR TITLE
Support the latest Atom

### LINKED ISSUE #7: Preview tabs do not work
See https://github.com/atom/tabs/issues/292

Root cause was this package.
## Steps to reproduce
1. Install this package
2. Ensure preview tabs are enabled (settings -> tabs -> ensure "Use preview tabs" is checked)
3. Open a file by single clicking
4. Observe that the title isn't italicized (indicates it being a preview tab)
5. Open another file by single clicking
6. Observe that it creates another tab

Side note: This was working fine up until a week or so ago, so root cause must be something that happened in an update. If you look at the issue I linked to above, you'll see some discussion around a new way Atom implements preview tabs, so perhaps that's why.

### PR DESCRIPTION
**Pull request by jspiro**
Also fixes #7.

### CODE REVIEW

**Comment by tiagocpontesp** [comment]
Does this fix https://github.com/mark-hahn/tab-smart-sort/issues/7 as well?

**Comment by jspiro** [comment]
I don't observe that problem, so I assume that it does! I'll update the description to mention that too.

**Comment by jspiro** [comment]
@mark-hahn I'd be willing to take over this plugin if you like.

**Comment by mark-hahn** [comment]
That would be great.  Let me figure out how to switch it.

**Comment by mark-hahn** [comment]
When I tried to transfer the repo it said you already had one with the same name.  Rename it and I'll try again.

**Comment by mark-hahn** [comment]
Thanks.  If you have a repo with the same name "tab-smart-sort" then you
have to rename your fork.  Otherwise I get an error when I try to transfer
ownership.  Something like "a repo already exists with that name".

Let me know when I can transfer.

**Comment by jspiro** [comment]
Renamed my repo, go ahead with the transfer! I'm not familiar with transferring the plugin ownership, but this looks like it might have some ideas: https://discuss.atom.io/t/need-maintainers-for-some-projects/13850/4

Do you know anything about that?

**Comment by mark-hahn** [comment]
Now when I tried to transfer I got "jspiro already has a repository in the mark-hahn/tab-smart-sort network".  I'm guessing that means you have a fork of it even though it's renamed, but that is just a guess.  I googled the error message and nothing explained what was meant by network.  Try saving your fork changes, deleting the fork, and then let me know again.

**Comment by jspiro** [comment]
Gotcha, I deleted my repo. Try again. FYI I found this http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#transferring-ownership -- so it looks like this is all you will have to do.

By the way, thanks for coming up with this idea and making the first version. I find it hugely useful.

**Comment by mark-hahn** [comment]
Done.

**Pull request merged**
